CREATE TABLE `ports` (
  `NEV` varchar(45) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'name',
  `ADAT` float(8,2) NOT NULL DEFAULT '0.00' COMMENT 'data',
  `MIEZ` varchar(40) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'subscription',
  `FAJTA` char(1) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'type: N or S (number or string)',
  `SZOVEG` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'if type is S, text is here',
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `IDO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'yyyymmddhhmmss',
  `CHANGE1` BOOLEAN DEFAULT FALSE COMMENT 'show if the row has been modified',
  `icon0` varchar(32) COLLATE utf8_bin NOT NULL DEFAULT 'instr_error.gif' COMMENT 'data: icon for not definied data',
  `value1` int(11) NOT NULL DEFAULT '0' COMMENT 'data: value1',
  `min1` int(11) NOT NULL COMMENT 'data is value1 if higher',
  `max1` int(11) NOT NULL COMMENT 'data is value1 if lower',
  `icon1` varchar(32) COLLATE utf8_bin NOT NULL DEFAULT 'instr_error.gif' COMMENT 'icon: value1 ',
  `x1` int(11) NOT NULL DEFAULT '10' COMMENT 'x coordinate for value1 on screen',
  `y1` int(11) NOT NULL COMMENT 'y  coordinate for value1 on screen',
  `value2` int(11) NOT NULL DEFAULT '1' COMMENT 'data: value2',
  `min2` int(11) NOT NULL COMMENT 'value2 if higher',
  `max2` int(11) NOT NULL COMMENT 'value2 if lower',
  `icon2` varchar(32) COLLATE utf8_bin NOT NULL DEFAULT 'icon: value2' COMMENT 'icon: value2',
  `x2` int(11) NOT NULL DEFAULT '20' COMMENT 'x coordinate for value2 on screen',
  `y2` int(11) NOT NULL DEFAULT '20' COMMENT 'y coordinate for value2 on screen',
  `value3` int(11) NOT NULL DEFAULT '3' COMMENT 'data: value3',
  `min3` int(11) NOT NULL COMMENT 'value3 if higher',
  `max3` int(11) NOT NULL COMMENT 'value3 if lower',
  `icon3` varchar(32) COLLATE utf8_bin NOT NULL DEFAULT 'icon: value3' COMMENT 'icon: value3',
  `x3` int(11) NOT NULL DEFAULT '30' COMMENT 'x coordinate for value3 on screen',
  `y3` int(11) NOT NULL DEFAULT '30' COMMENT 'y coordinate for value3 on screen',
  PRIMARY KEY (`ID`),
  KEY `ID` (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=1634 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='ports for apps or handler'